namespace TrimangoCalendar.Core.Entities;

public class GuestNote { public Guid Id { get; set; } public Guid GuestId { get; set; } public string? Note { get; set; } public string? CreatedBy { get; set; } public DateTime CreatedAt { get; set; } public Guest? Guest { get; set; } }
public class AgencyCommission { public Guid Id { get; set; } public Guid AgencyId { get; set; } public Guid PropertyId { get; set; } public Guid ReservationId { get; set; } public decimal Amount { get; set; } public decimal CommissionRate { get; set; } public string CurrencyCode { get; set; } = "TRY"; public string Status { get; set; } = "Pending"; public DateTime? PaidAt { get; set; } public decimal? MinCommissionRate { get; set; } public decimal? MaxCommissionRate { get; set; } public DateTime ValidFrom { get; set; } public DateTime? ValidTo { get; set; } public bool IsActive { get; set; } public DateTime CreatedAt { get; set; } public Agency? Agency { get; set; } public Property? Property { get; set; } public Reservation? Reservation { get; set; } }
public class SpecialDayRate { public Guid Id { get; set; } public Guid PropertyId { get; set; } public Guid? UnitId { get; set; } public DateTime Date { get; set; } public decimal Price { get; set; } public string CurrencyCode { get; set; } = "TRY"; public string? Description { get; set; } public bool IsActive { get; set; } public Unit? Unit { get; set; } }
public class PromotionUsage { public Guid Id { get; set; } public Guid PromotionId { get; set; } public Guid ReservationId { get; set; } public decimal DiscountAmount { get; set; } public DateTime UsedAt { get; set; } public Promotion? Promotion { get; set; } }
public class CurrencyFormat { public Guid Id { get; set; } public string CurrencyCode { get; set; } = "TRY"; public string Symbol { get; set; } = "₺"; public string Pattern { get; set; } = "{0} {1}"; }
public class CalendarEvent { public Guid Id { get; set; } public Guid PropertyId { get; set; } public Guid? UnitId { get; set; } public string Title { get; set; } = string.Empty; public DateTime StartDate { get; set; } public DateTime EndDate { get; set; } }
public class CalendarNote { public Guid Id { get; set; } public Guid PropertyId { get; set; } public DateTime Date { get; set; } public string Note { get; set; } = string.Empty; }
public class NotificationLog { public Guid Id { get; set; } public Guid NotificationId { get; set; } public string Channel { get; set; } = string.Empty; public string? Status { get; set; } public DateTime CreatedAt { get; set; } }
public class WidgetTheme { public Guid Id { get; set; } public Guid WidgetId { get; set; } public string Name { get; set; } = string.Empty; public string? ConfigJson { get; set; } }
public class ReportSchedule { public Guid Id { get; set; } public Guid TenantId { get; set; } public string ReportType { get; set; } = string.Empty; public string CronExpression { get; set; } = string.Empty; public bool IsActive { get; set; } }
public class DashboardWidget { public Guid Id { get; set; } public Guid TenantId { get; set; } public string WidgetType { get; set; } = string.Empty; public string? ConfigJson { get; set; } public int SortOrder { get; set; } }
public class AuditLog { public Guid Id { get; set; } public Guid TenantId { get; set; } public string EntityName { get; set; } = string.Empty; public string EntityId { get; set; } = string.Empty; public string Action { get; set; } = string.Empty; public string? OldValues { get; set; } public string? NewValues { get; set; } public string? UserId { get; set; } public string? IpAddress { get; set; } public string? Data { get; set; } public DateTime CreatedAt { get; set; } public string? CreatedBy { get; set; } }
public class SystemSetting { public Guid Id { get; set; } public string Key { get; set; } = string.Empty; public string Value { get; set; } = string.Empty; }
public class EmailTemplate { public Guid Id { get; set; } public string Code { get; set; } = string.Empty; public string Subject { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; public bool IsActive { get; set; } }
public class SmsTemplate { public Guid Id { get; set; } public string Code { get; set; } = string.Empty; public string Body { get; set; } = string.Empty; public bool IsActive { get; set; } }
public partial class ReservationPayment { public string? PaymentMethod { get; set; } public string? TransactionId { get; set; } public string Status { get; set; } = "Pending"; public DateTime CreatedAt { get; set; } public Reservation? Reservation { get; set; } }
public partial class GuestDocument { public string? FilePath { get; set; } public DateTime UploadedAt { get; set; } public Guest? Guest { get; set; } }
